// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aonuxguslyainpjyylgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbnV4Z3VzbHlhaW5wanl5bGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTQzMjYsImV4cCI6MjA2MjgzMDMyNn0.9dW9uDTQh9KXGEgea853sbaReFbjBr1UveZ7BkQzfz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);